### ISSUE TITLE
LimeDrop.org doesn't work properly on Firefox ?

### ISSUE THREAD

**Issue by Ricola3D** [noah-/limedrop#1]
Hello,

Just a message to track the fact that there are JS errors on Firefox : it fails to load the <script> element whose source is « http://limedrop.org/js/CryptoJS/crypto-js.js »

Have you ever met this issue ?

My Firefox version is 62.0 (64 bits)

**Comment by noah-** [comment]
You must have some adon blocking it. I just clicked the link and it works fine.

**Comment by Ricola3D** [comment]
You were right thanks. I tried with Firefox in safemode, and with disabling all my plugins one by one.

I don't know why, but it is **Adblock Plus** that prevents this script from loading. So for the moment a workaoround is to disable this plugin for limedrop webpage

**Comment by noah-** [comment]
or you can probably just whitelist the crypto-js script
